### PR TITLE
Execute DAX Query Against Dataset & Gateways as Admin

### PR DESCRIPTION
**Pull request by tirnovar**
I am adding a function for executing DAX query against selected dataset.

### CODE REVIEW

**Comment by tirnovar** [comment]
I have also added Gateways as Admin.

**Comment by tirnovar** [comment]
Added Scanner API

**Comment by tirnovar** [comment]
Hey, I have also added a call for receiving results. It is built with the call for receiving status, and if it is "Success," it will call for results. But now, it is just for "one" workspace. I tested it with other Power BI Admins in Dataflows with Service Principals, and it worked smoothly in combining two dataflows.

I will push a later version that will allow you to send a list of them, and it will split all calls into lists with 100 ids to optimize calls.

**Comment by klinejordan** [comment]
@tirnovar Thanks so much for contributing, your M is a lot better than mine! :)

Some feedback:

- Given that the APIs used by the Power Platform Admin Center (v2.0) are undocumented and unsupported, can you move those to the Experimental navigation folder?
- For the Metrics stuff, is there a reason you went with a function instead of a query? Most of the workspace-level calls just retrieve everything from all workspaces the user has access to, and lets them sort it by workspace after the fact. That's the pattern I would have implemented but curious to hear why you went with a function? 
- I have similar concerns as @lbendlin about the Scanner API stuff because the first feedback you'll probably get is "this is great but can you just scan my entire tenant". For now, I'd just put in some more detailed instructions on the README about how to use the scanner functions since this is the first time we're asking users to simulate polling in the API and some users may not know that they need to copy and paste the scan ID into the parameters of the Results Of Scan function

**Comment by klinejordan** [comment]
Also wouldn't assume that all DAX queries start with EVALUATE - many start with DEFINE and I would definitely remove the hard-coded EVALUATE as the start of the query

**Comment by tirnovar** [comment]
First of all, thank you for the compliment 😊.  I will move those Gateways to experimental, but it is a regular call made by the Admin.PowerPlatform.com service. Receiving all gateways through v2 only supports User tokens and not App tokens for verification.  That is their big difference today.  As for Metrics, they are functions for a simple reason.  Their Admin form does not exist today.  So I run them against a workspace I don't have access to, so I get an error (even though I'm Admin).  For that reason, it is also written that way in the note for that function.  I will edit the README to explain how to work with the Scanner API and add a version that will address the possibility of entering list workspaces.  As for ExecuteQueries, this endpoint can handle various options, but I wouldn't give people the option to create variables in the DEFINE part as part of it.  But if you want them there, it's no problem for me to add them there.

**Pull request merged**
