### PR TITLE
I added Pages to get all the pages of the reports

### PR DESCRIPTION
**Pull request by David-Rousselle**

### CODE REVIEW

**Review by klinejordan — CHANGES_REQUESTED** [review]
Thanks for contributing! just made some small taxonomy changes, can you modify the PR to include those?

**Comment by David-Rousselle** [comment]
Done, I hope it's what you asked :)

**Review by klinejordan — CHANGES_REQUESTED** [review]
Okay sorry one last change to simplify the M a little bit, explicitly type the columns and remove some extraneous attributes. If you could push a new copy of the .mez to your fork I will approve this PR

**Comment by David-Rousselle** [comment]
thank you, I'm a github and M newbie, I learned a lot

**Pull request merged**
